// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  formDataBodySerializer,
} from "@hey-api/client-fetch";
import type {
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponse,
  DatabaseHealthCheckHealthDbGetData,
  DatabaseHealthCheckHealthDbGetResponse,
  HealthRedisHealthRedisGetData,
  HealthRedisHealthRedisGetResponse,
  ReadinessCheckHealthReadyGetData,
  ReadinessCheckHealthReadyGetResponse,
  LoginApiV1AuthLoginPostData,
  LoginApiV1AuthLoginPostResponse,
  LoginApiV1AuthLoginPostError,
  RefreshTokenApiV1AuthRefreshPostData,
  RefreshTokenApiV1AuthRefreshPostResponse,
  RefreshTokenApiV1AuthRefreshPostError,
  LogoutApiV1AuthLogoutPostData,
  LogoutApiV1AuthLogoutPostResponse,
  ResetPasswordApiV1AuthResetPasswordPostData,
  ResetPasswordApiV1AuthResetPasswordPostResponse,
  ResetPasswordApiV1AuthResetPasswordPostError,
  SeedDemoUsersApiV1AuthSeedPostData,
  SeedDemoUsersApiV1AuthSeedPostResponse,
  ListUsersApiV1AuthUsersGetData,
  ListUsersApiV1AuthUsersGetResponse,
  ListUsersApiV1AuthUsersGetError,
  CreateUserApiV1AuthUsersPostData,
  CreateUserApiV1AuthUsersPostResponse,
  CreateUserApiV1AuthUsersPostError,
  DeleteUserDataApiV1AuthUsersUserIdDeleteData,
  DeleteUserDataApiV1AuthUsersUserIdDeleteResponse,
  DeleteUserDataApiV1AuthUsersUserIdDeleteError,
  GetUserApiV1AuthUsersUserIdGetData,
  GetUserApiV1AuthUsersUserIdGetResponse,
  GetUserApiV1AuthUsersUserIdGetError,
  UpdateUserApiV1AuthUsersUserIdPatchData,
  UpdateUserApiV1AuthUsersUserIdPatchResponse,
  UpdateUserApiV1AuthUsersUserIdPatchError,
  ChatCompletionsV1ChatCompletionsPostData,
  ChatCompletionsV1ChatCompletionsPostResponse,
  ChatCompletionsV1ChatCompletionsPostError,
  ListModelsV1ModelsGetData,
  ListModelsV1ModelsGetResponse,
  GetVehiclesApiV1TransitVehiclesGetData,
  GetVehiclesApiV1TransitVehiclesGetResponse,
  GetVehiclesApiV1TransitVehiclesGetError,
  GetFeedsApiV1TransitFeedsGetData,
  GetFeedsApiV1TransitFeedsGetResponse,
  GetVehicleHistoryApiV1TransitVehiclesVehicleIdHistoryGetData,
  GetVehicleHistoryApiV1TransitVehiclesVehicleIdHistoryGetResponse,
  GetVehicleHistoryApiV1TransitVehiclesVehicleIdHistoryGetError,
  GetRouteDelayTrendApiV1TransitRoutesRouteIdDelayTrendGetData,
  GetRouteDelayTrendApiV1TransitRoutesRouteIdDelayTrendGetResponse,
  GetRouteDelayTrendApiV1TransitRoutesRouteIdDelayTrendGetError,
  ListStopsApiV1StopsGetData,
  ListStopsApiV1StopsGetResponse,
  ListStopsApiV1StopsGetError,
  CreateStopApiV1StopsPostData,
  CreateStopApiV1StopsPostResponse,
  CreateStopApiV1StopsPostError,
  ListAllStopsForMapApiV1StopsMapGetData,
  ListAllStopsForMapApiV1StopsMapGetResponse,
  ListTerminalStopIdsApiV1StopsTerminalsGetData,
  ListTerminalStopIdsApiV1StopsTerminalsGetResponse,
  NearbyStopsApiV1StopsNearbyGetData,
  NearbyStopsApiV1StopsNearbyGetResponse,
  NearbyStopsApiV1StopsNearbyGetError,
  DeleteStopApiV1StopsStopIdDeleteData,
  DeleteStopApiV1StopsStopIdDeleteResponse,
  DeleteStopApiV1StopsStopIdDeleteError,
  GetStopApiV1StopsStopIdGetData,
  GetStopApiV1StopsStopIdGetResponse,
  GetStopApiV1StopsStopIdGetError,
  UpdateStopApiV1StopsStopIdPatchData,
  UpdateStopApiV1StopsStopIdPatchResponse,
  UpdateStopApiV1StopsStopIdPatchError,
  ListDocumentsApiV1KnowledgeDocumentsGetData,
  ListDocumentsApiV1KnowledgeDocumentsGetResponse,
  ListDocumentsApiV1KnowledgeDocumentsGetError,
  UploadDocumentApiV1KnowledgeDocumentsPostData,
  UploadDocumentApiV1KnowledgeDocumentsPostResponse,
  UploadDocumentApiV1KnowledgeDocumentsPostError,
  DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteData,
  DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteResponse,
  DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteError,
  GetDocumentApiV1KnowledgeDocumentsDocumentIdGetData,
  GetDocumentApiV1KnowledgeDocumentsDocumentIdGetResponse,
  GetDocumentApiV1KnowledgeDocumentsDocumentIdGetError,
  UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchData,
  UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchResponse,
  UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchError,
  DownloadDocumentApiV1KnowledgeDocumentsDocumentIdDownloadGetData,
  DownloadDocumentApiV1KnowledgeDocumentsDocumentIdDownloadGetError,
  GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetData,
  GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetResponse,
  GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetError,
  ListDomainsApiV1KnowledgeDomainsGetData,
  ListDomainsApiV1KnowledgeDomainsGetResponse,
  ListTagsApiV1KnowledgeTagsGetData,
  ListTagsApiV1KnowledgeTagsGetResponse,
  CreateTagApiV1KnowledgeTagsPostData,
  CreateTagApiV1KnowledgeTagsPostResponse,
  CreateTagApiV1KnowledgeTagsPostError,
  DeleteTagApiV1KnowledgeTagsTagIdDeleteData,
  DeleteTagApiV1KnowledgeTagsTagIdDeleteResponse,
  DeleteTagApiV1KnowledgeTagsTagIdDeleteError,
  AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostData,
  AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostResponse,
  AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostError,
  RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteData,
  RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteResponse,
  RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteError,
  SearchKnowledgeApiV1KnowledgeSearchPostData,
  SearchKnowledgeApiV1KnowledgeSearchPostResponse,
  SearchKnowledgeApiV1KnowledgeSearchPostError,
  ListAgenciesApiV1SchedulesAgenciesGetData,
  ListAgenciesApiV1SchedulesAgenciesGetResponse,
  ListAgenciesApiV1SchedulesAgenciesGetError,
  CreateAgencyApiV1SchedulesAgenciesPostData,
  CreateAgencyApiV1SchedulesAgenciesPostResponse,
  CreateAgencyApiV1SchedulesAgenciesPostError,
  ListRoutesApiV1SchedulesRoutesGetData,
  ListRoutesApiV1SchedulesRoutesGetResponse,
  ListRoutesApiV1SchedulesRoutesGetError,
  CreateRouteApiV1SchedulesRoutesPostData,
  CreateRouteApiV1SchedulesRoutesPostResponse,
  CreateRouteApiV1SchedulesRoutesPostError,
  DeleteRouteApiV1SchedulesRoutesRouteIdDeleteData,
  DeleteRouteApiV1SchedulesRoutesRouteIdDeleteResponse,
  DeleteRouteApiV1SchedulesRoutesRouteIdDeleteError,
  GetRouteApiV1SchedulesRoutesRouteIdGetData,
  GetRouteApiV1SchedulesRoutesRouteIdGetResponse,
  GetRouteApiV1SchedulesRoutesRouteIdGetError,
  UpdateRouteApiV1SchedulesRoutesRouteIdPatchData,
  UpdateRouteApiV1SchedulesRoutesRouteIdPatchResponse,
  UpdateRouteApiV1SchedulesRoutesRouteIdPatchError,
  ListCalendarsApiV1SchedulesCalendarsGetData,
  ListCalendarsApiV1SchedulesCalendarsGetResponse,
  ListCalendarsApiV1SchedulesCalendarsGetError,
  CreateCalendarApiV1SchedulesCalendarsPostData,
  CreateCalendarApiV1SchedulesCalendarsPostResponse,
  CreateCalendarApiV1SchedulesCalendarsPostError,
  DeleteCalendarApiV1SchedulesCalendarsCalendarIdDeleteData,
  DeleteCalendarApiV1SchedulesCalendarsCalendarIdDeleteResponse,
  DeleteCalendarApiV1SchedulesCalendarsCalendarIdDeleteError,
  GetCalendarApiV1SchedulesCalendarsCalendarIdGetData,
  GetCalendarApiV1SchedulesCalendarsCalendarIdGetResponse,
  GetCalendarApiV1SchedulesCalendarsCalendarIdGetError,
  UpdateCalendarApiV1SchedulesCalendarsCalendarIdPatchData,
  UpdateCalendarApiV1SchedulesCalendarsCalendarIdPatchResponse,
  UpdateCalendarApiV1SchedulesCalendarsCalendarIdPatchError,
  AddCalendarExceptionApiV1SchedulesCalendarsCalendarIdExceptionsPostData,
  AddCalendarExceptionApiV1SchedulesCalendarsCalendarIdExceptionsPostResponse,
  AddCalendarExceptionApiV1SchedulesCalendarsCalendarIdExceptionsPostError,
  RemoveCalendarExceptionApiV1SchedulesCalendarExceptionsExceptionIdDeleteData,
  RemoveCalendarExceptionApiV1SchedulesCalendarExceptionsExceptionIdDeleteResponse,
  RemoveCalendarExceptionApiV1SchedulesCalendarExceptionsExceptionIdDeleteError,
  ListTripsApiV1SchedulesTripsGetData,
  ListTripsApiV1SchedulesTripsGetResponse,
  ListTripsApiV1SchedulesTripsGetError,
  CreateTripApiV1SchedulesTripsPostData,
  CreateTripApiV1SchedulesTripsPostResponse,
  CreateTripApiV1SchedulesTripsPostError,
  DeleteTripApiV1SchedulesTripsTripIdDeleteData,
  DeleteTripApiV1SchedulesTripsTripIdDeleteResponse,
  DeleteTripApiV1SchedulesTripsTripIdDeleteError,
  GetTripApiV1SchedulesTripsTripIdGetData,
  GetTripApiV1SchedulesTripsTripIdGetResponse,
  GetTripApiV1SchedulesTripsTripIdGetError,
  UpdateTripApiV1SchedulesTripsTripIdPatchData,
  UpdateTripApiV1SchedulesTripsTripIdPatchResponse,
  UpdateTripApiV1SchedulesTripsTripIdPatchError,
  ReplaceStopTimesApiV1SchedulesTripsTripIdStopTimesPutData,
  ReplaceStopTimesApiV1SchedulesTripsTripIdStopTimesPutResponse,
  ReplaceStopTimesApiV1SchedulesTripsTripIdStopTimesPutError,
  ExportGtfsApiV1SchedulesExportGetData,
  ExportGtfsApiV1SchedulesExportGetError,
  ImportGtfsApiV1SchedulesImportPostData,
  ImportGtfsApiV1SchedulesImportPostResponse,
  ImportGtfsApiV1SchedulesImportPostError,
  ValidateScheduleApiV1SchedulesValidatePostData,
  ValidateScheduleApiV1SchedulesValidatePostResponse,
  ListDriversApiV1DriversGetData,
  ListDriversApiV1DriversGetResponse,
  ListDriversApiV1DriversGetError,
  CreateDriverApiV1DriversPostData,
  CreateDriverApiV1DriversPostResponse,
  CreateDriverApiV1DriversPostError,
  DeleteDriverApiV1DriversDriverIdDeleteData,
  DeleteDriverApiV1DriversDriverIdDeleteResponse,
  DeleteDriverApiV1DriversDriverIdDeleteError,
  GetDriverApiV1DriversDriverIdGetData,
  GetDriverApiV1DriversDriverIdGetResponse,
  GetDriverApiV1DriversDriverIdGetError,
  UpdateDriverApiV1DriversDriverIdPatchData,
  UpdateDriverApiV1DriversDriverIdPatchResponse,
  UpdateDriverApiV1DriversDriverIdPatchError,
  ListEventsApiV1EventsGetData,
  ListEventsApiV1EventsGetResponse,
  ListEventsApiV1EventsGetError,
  CreateEventApiV1EventsPostData,
  CreateEventApiV1EventsPostResponse,
  CreateEventApiV1EventsPostError,
  ListEventsByDriverApiV1EventsByDriverDriverIdGetData,
  ListEventsByDriverApiV1EventsByDriverDriverIdGetResponse,
  ListEventsByDriverApiV1EventsByDriverDriverIdGetError,
  DeleteEventApiV1EventsEventIdDeleteData,
  DeleteEventApiV1EventsEventIdDeleteResponse,
  DeleteEventApiV1EventsEventIdDeleteError,
  GetEventApiV1EventsEventIdGetData,
  GetEventApiV1EventsEventIdGetResponse,
  GetEventApiV1EventsEventIdGetError,
  UpdateEventApiV1EventsEventIdPatchData,
  UpdateEventApiV1EventsEventIdPatchResponse,
  UpdateEventApiV1EventsEventIdPatchError,
  ListSkillsApiV1SkillsGetData,
  ListSkillsApiV1SkillsGetResponse,
  ListSkillsApiV1SkillsGetError,
  CreateSkillApiV1SkillsPostData,
  CreateSkillApiV1SkillsPostResponse,
  CreateSkillApiV1SkillsPostError,
  DeleteSkillApiV1SkillsSkillIdDeleteData,
  DeleteSkillApiV1SkillsSkillIdDeleteResponse,
  DeleteSkillApiV1SkillsSkillIdDeleteError,
  GetSkillApiV1SkillsSkillIdGetData,
  GetSkillApiV1SkillsSkillIdGetResponse,
  GetSkillApiV1SkillsSkillIdGetError,
  UpdateSkillApiV1SkillsSkillIdPatchData,
  UpdateSkillApiV1SkillsSkillIdPatchResponse,
  UpdateSkillApiV1SkillsSkillIdPatchError,
  SeedSkillsApiV1SkillsSeedPostData,
  SeedSkillsApiV1SkillsSeedPostResponse,
  ListVehiclesApiV1VehiclesGetData,
  ListVehiclesApiV1VehiclesGetResponse,
  ListVehiclesApiV1VehiclesGetError,
  CreateVehicleApiV1VehiclesPostData,
  CreateVehicleApiV1VehiclesPostResponse,
  CreateVehicleApiV1VehiclesPostError,
  DeleteVehicleApiV1VehiclesVehicleIdDeleteData,
  DeleteVehicleApiV1VehiclesVehicleIdDeleteResponse,
  DeleteVehicleApiV1VehiclesVehicleIdDeleteError,
  GetVehicleApiV1VehiclesVehicleIdGetData,
  GetVehicleApiV1VehiclesVehicleIdGetResponse,
  GetVehicleApiV1VehiclesVehicleIdGetError,
  UpdateVehicleApiV1VehiclesVehicleIdPatchData,
  UpdateVehicleApiV1VehiclesVehicleIdPatchResponse,
  UpdateVehicleApiV1VehiclesVehicleIdPatchError,
  AssignDriverApiV1VehiclesVehicleIdAssignDriverPostData,
  AssignDriverApiV1VehiclesVehicleIdAssignDriverPostResponse,
  AssignDriverApiV1VehiclesVehicleIdAssignDriverPostError,
  GetMaintenanceHistoryApiV1VehiclesVehicleIdMaintenanceGetData,
  GetMaintenanceHistoryApiV1VehiclesVehicleIdMaintenanceGetResponse,
  GetMaintenanceHistoryApiV1VehiclesVehicleIdMaintenanceGetError,
  CreateMaintenanceRecordApiV1VehiclesVehicleIdMaintenancePostData,
  CreateMaintenanceRecordApiV1VehiclesVehicleIdMaintenancePostResponse,
  CreateMaintenanceRecordApiV1VehiclesVehicleIdMaintenancePostError,
  ExportNetexApiV1ComplianceNetexGetData,
  ExportNetexApiV1ComplianceNetexGetError,
  GetSiriVmApiV1ComplianceSiriVmGetData,
  GetSiriVmApiV1ComplianceSiriVmGetError,
  GetSiriSmApiV1ComplianceSiriSmGetData,
  GetSiriSmApiV1ComplianceSiriSmGetError,
  GetExportStatusApiV1ComplianceStatusGetData,
  GetExportStatusApiV1ComplianceStatusGetResponse,
  GetFleetSummaryApiV1AnalyticsFleetSummaryGetData,
  GetFleetSummaryApiV1AnalyticsFleetSummaryGetResponse,
  GetDriverSummaryApiV1AnalyticsDriverSummaryGetData,
  GetDriverSummaryApiV1AnalyticsDriverSummaryGetResponse,
  GetOnTimePerformanceApiV1AnalyticsOnTimePerformanceGetData,
  GetOnTimePerformanceApiV1AnalyticsOnTimePerformanceGetResponse,
  GetOnTimePerformanceApiV1AnalyticsOnTimePerformanceGetError,
  GetOverviewApiV1AnalyticsOverviewGetData,
  GetOverviewApiV1AnalyticsOverviewGetResponse,
  ReadRootGetData,
  ReadRootGetResponse,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health Check
 * Basic health check endpoint.
 *
 * Args:
 * request: The incoming HTTP request (used for rate limiting).
 *
 * Returns:
 * dict: Health status of the API service.
 *
 * Example response:
 * {"status": "healthy", "service": "api"}
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    HealthCheckHealthGetResponse,
    unknown,
    ThrowOnError
  >({
    url: "/health",
    ...options,
  });
};

/**
 * Database Health Check
 * Database connectivity health check with 10s result caching.
 *
 * Caches successful results for 10 seconds to prevent connection pool
 * exhaustion from frequent health check polling.
 *
 * Args:
 * request: The incoming HTTP request (used for rate limiting).
 * db: Database session dependency.
 *
 * Returns:
 * dict: Health status of the database connection.
 *
 * Raises:
 * HTTPException: 503 if database is not accessible.
 */
export const databaseHealthCheckHealthDbGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DatabaseHealthCheckHealthDbGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    DatabaseHealthCheckHealthDbGetResponse,
    unknown,
    ThrowOnError
  >({
    url: "/health/db",
    ...options,
  });
};

/**
 * Health Redis
 * Redis health check with 10s result caching.
 *
 * Args:
 * request: The incoming HTTP request (used for rate limiting).
 *
 * Returns:
 * dict: Health status of the Redis connection.
 *
 * Raises:
 * HTTPException: 503 if Redis is not accessible.
 */
export const healthRedisHealthRedisGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthRedisHealthRedisGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    HealthRedisHealthRedisGetResponse,
    unknown,
    ThrowOnError
  >({
    url: "/health/redis",
    ...options,
  });
};

/**
 * Readiness Check
 * Readiness check for all application dependencies.
 *
 * Verifies that the application is ready to serve requests by checking
 * all critical dependencies (database, configuration, Redis, etc.).
 *
 * Args:
 * request: The incoming HTTP request (used for rate limiting).
 * db: Database session dependency.
 *
 * Returns:
 * dict: Readiness status with environment and dependency information.
 *
 * Raises:
 * HTTPException: 503 if any dependency is not ready.
 */
export const readinessCheckHealthReadyGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ReadinessCheckHealthReadyGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadinessCheckHealthReadyGetResponse,
    unknown,
    ThrowOnError
  >({
    url: "/health/ready",
    ...options,
  });
};

/**
 * Login
 * Authenticate user with email and password. Returns JWT tokens.
 */
export const loginApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginApiV1AuthLoginPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    LoginApiV1AuthLoginPostResponse,
    LoginApiV1AuthLoginPostError,
    ThrowOnError
  >({
    url: "/api/v1/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Refresh Token
 * Exchange a valid refresh token for a new access token.
 */
export const refreshTokenApiV1AuthRefreshPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RefreshTokenApiV1AuthRefreshPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    RefreshTokenApiV1AuthRefreshPostResponse,
    RefreshTokenApiV1AuthRefreshPostError,
    ThrowOnError
  >({
    url: "/api/v1/auth/refresh",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Logout
 * Revoke the current access token, effectively logging out.
 */
export const logoutApiV1AuthLogoutPost = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutApiV1AuthLogoutPostData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    LogoutApiV1AuthLogoutPostResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/logout",
    ...options,
  });
};

/**
 * Reset Password
 * Reset a user's password (admin only).
 */
export const resetPasswordApiV1AuthResetPasswordPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ResetPasswordApiV1AuthResetPasswordPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ResetPasswordApiV1AuthResetPasswordPostResponse,
    ResetPasswordApiV1AuthResetPasswordPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Seed Demo Users
 * Seed demo users (development only, admin-only, no-op if users exist).
 */
export const seedDemoUsersApiV1AuthSeedPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SeedDemoUsersApiV1AuthSeedPostData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    SeedDemoUsersApiV1AuthSeedPostResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/seed",
    ...options,
  });
};

/**
 * List Users
 * List all users with pagination and filters (admin only).
 */
export const listUsersApiV1AuthUsersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListUsersApiV1AuthUsersGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListUsersApiV1AuthUsersGetResponse,
    ListUsersApiV1AuthUsersGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/users",
    ...options,
  });
};

/**
 * Create User
 * Create a new user (admin only).
 */
export const createUserApiV1AuthUsersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateUserApiV1AuthUsersPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateUserApiV1AuthUsersPostResponse,
    CreateUserApiV1AuthUsersPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete User Data
 * Delete user data for GDPR right-to-erasure compliance.
 *
 * Admin-only. Permanently removes user record and clears associated
 * Redis tracking data. Cannot delete own account.
 */
export const deleteUserDataApiV1AuthUsersUserIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteUserDataApiV1AuthUsersUserIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteUserDataApiV1AuthUsersUserIdDeleteResponse,
    DeleteUserDataApiV1AuthUsersUserIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/users/{user_id}",
    ...options,
  });
};

/**
 * Get User
 * Get a single user by ID (admin only).
 */
export const getUserApiV1AuthUsersUserIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUserApiV1AuthUsersUserIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetUserApiV1AuthUsersUserIdGetResponse,
    GetUserApiV1AuthUsersUserIdGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/users/{user_id}",
    ...options,
  });
};

/**
 * Update User
 * Update a user's profile (admin only).
 */
export const updateUserApiV1AuthUsersUserIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateUserApiV1AuthUsersUserIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateUserApiV1AuthUsersUserIdPatchResponse,
    UpdateUserApiV1AuthUsersUserIdPatchError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/users/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Chat Completions
 * Create a chat completion.
 *
 * Accepts a list of messages and returns the agent's response
 * in OpenAI-compatible format.
 *
 * Args:
 * request: The incoming HTTP request (used for rate limiting).
 * body: Chat completion request with messages.
 * service: Agent service instance (injected).
 *
 * Returns:
 * Chat completion response with the agent's message.
 */
export const chatCompletionsV1ChatCompletionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ChatCompletionsV1ChatCompletionsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ChatCompletionsV1ChatCompletionsPostResponse,
    ChatCompletionsV1ChatCompletionsPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/chat/completions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List Models
 * List available models.
 *
 * Returns the currently configured LLM model information.
 *
 * Returns:
 * Dictionary with model list in OpenAI-compatible format.
 */
export const listModelsV1ModelsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListModelsV1ModelsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListModelsV1ModelsGetResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v1/models",
    ...options,
  });
};

/**
 * Get Vehicles
 * Get real-time vehicle positions, optionally filtered by feed and/or route.
 *
 * Args:
 * request: The incoming HTTP request (used for rate limiting).
 * route_id: Optional GTFS route ID to filter results.
 * feed_id: Optional feed source to filter results (e.g., "riga").
 *
 * Returns:
 * VehiclePositionsResponse with vehicle positions.
 *
 * Raises:
 * TransitDataError: Mapped to HTTP 503 by global exception handler.
 */
export const getVehiclesApiV1TransitVehiclesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetVehiclesApiV1TransitVehiclesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetVehiclesApiV1TransitVehiclesGetResponse,
    GetVehiclesApiV1TransitVehiclesGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/transit/vehicles",
    ...options,
  });
};

/**
 * Get Feeds
 * List configured transit feeds and their status.
 */
export const getFeedsApiV1TransitFeedsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetFeedsApiV1TransitFeedsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetFeedsApiV1TransitFeedsGetResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/transit/feeds",
    ...options,
  });
};

/**
 * Get Vehicle History
 * Get historical positions for a specific vehicle within a time range.
 *
 * Requires admin, dispatcher, or editor role. Rate limited to 10/minute.
 *
 * Args:
 * request: HTTP request (rate limiting).
 * vehicle_id: Fleet vehicle identifier.
 * from_time: ISO 8601 start time (UTC).
 * to_time: ISO 8601 end time (UTC).
 * limit: Maximum positions to return (1-10000, default 1000).
 * db: Async database session.
 *
 * Returns:
 * VehicleHistoryResponse with ordered position history.
 */
export const getVehicleHistoryApiV1TransitVehiclesVehicleIdHistoryGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetVehicleHistoryApiV1TransitVehiclesVehicleIdHistoryGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    GetVehicleHistoryApiV1TransitVehiclesVehicleIdHistoryGetResponse,
    GetVehicleHistoryApiV1TransitVehiclesVehicleIdHistoryGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/transit/vehicles/{vehicle_id}/history",
    ...options,
  });
};

/**
 * Get Route Delay Trend
 * Get aggregated delay trend for a route over a time range.
 *
 * Uses TimescaleDB time_bucket for efficient time-series aggregation.
 * Rate limited to 10/minute.
 *
 * Args:
 * request: HTTP request (rate limiting).
 * route_id: GTFS route identifier.
 * from_time: ISO 8601 start time (UTC).
 * to_time: ISO 8601 end time (UTC).
 * interval_minutes: Time bucket size (5-1440 minutes, default 60).
 * db: Async database session.
 *
 * Returns:
 * RouteDelayTrendResponse with time-bucketed delay data.
 */
export const getRouteDelayTrendApiV1TransitRoutesRouteIdDelayTrendGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetRouteDelayTrendApiV1TransitRoutesRouteIdDelayTrendGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    GetRouteDelayTrendApiV1TransitRoutesRouteIdDelayTrendGetResponse,
    GetRouteDelayTrendApiV1TransitRoutesRouteIdDelayTrendGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/transit/routes/{route_id}/delay-trend",
    ...options,
  });
};

/**
 * List Stops
 * List stops with pagination and optional search filter.
 */
export const listStopsApiV1StopsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListStopsApiV1StopsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListStopsApiV1StopsGetResponse,
    ListStopsApiV1StopsGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/stops/",
    ...options,
  });
};

/**
 * Create Stop
 * Create a new stop.
 */
export const createStopApiV1StopsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateStopApiV1StopsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateStopApiV1StopsPostResponse,
    CreateStopApiV1StopsPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/stops/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List All Stops For Map
 * Return all stops in a single response (for map display).
 */
export const listAllStopsForMapApiV1StopsMapGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListAllStopsForMapApiV1StopsMapGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListAllStopsForMapApiV1StopsMapGetResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/stops/map",
    ...options,
  });
};

/**
 * List Terminal Stop Ids
 * Return IDs of stops that are the last stop of any trip (terminals/galapunkti).
 */
export const listTerminalStopIdsApiV1StopsTerminalsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListTerminalStopIdsApiV1StopsTerminalsGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListTerminalStopIdsApiV1StopsTerminalsGetResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/stops/terminals",
    ...options,
  });
};

/**
 * Nearby Stops
 * Find stops within a radius of a geographic point.
 */
export const nearbyStopsApiV1StopsNearbyGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<NearbyStopsApiV1StopsNearbyGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    NearbyStopsApiV1StopsNearbyGetResponse,
    NearbyStopsApiV1StopsNearbyGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/stops/nearby",
    ...options,
  });
};

/**
 * Delete Stop
 * Delete a stop by its database ID.
 */
export const deleteStopApiV1StopsStopIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteStopApiV1StopsStopIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteStopApiV1StopsStopIdDeleteResponse,
    DeleteStopApiV1StopsStopIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/stops/{stop_id}",
    ...options,
  });
};

/**
 * Get Stop
 * Get a stop by its database ID.
 */
export const getStopApiV1StopsStopIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetStopApiV1StopsStopIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetStopApiV1StopsStopIdGetResponse,
    GetStopApiV1StopsStopIdGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/stops/{stop_id}",
    ...options,
  });
};

/**
 * Update Stop
 * Update an existing stop.
 */
export const updateStopApiV1StopsStopIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateStopApiV1StopsStopIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateStopApiV1StopsStopIdPatchResponse,
    UpdateStopApiV1StopsStopIdPatchError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/stops/{stop_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List Documents
 * List documents with pagination and optional filtering.
 */
export const listDocumentsApiV1KnowledgeDocumentsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListDocumentsApiV1KnowledgeDocumentsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListDocumentsApiV1KnowledgeDocumentsGetResponse,
    ListDocumentsApiV1KnowledgeDocumentsGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/knowledge/documents",
    ...options,
  });
};

/**
 * Upload Document
 * Upload and ingest a document into the knowledge base.
 */
export const uploadDocumentApiV1KnowledgeDocumentsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UploadDocumentApiV1KnowledgeDocumentsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    UploadDocumentApiV1KnowledgeDocumentsPostResponse,
    UploadDocumentApiV1KnowledgeDocumentsPostError,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/knowledge/documents",
    ...options,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
  });
};

/**
 * Delete Document
 * Delete a document and its chunks.
 */
export const deleteDocumentApiV1KnowledgeDocumentsDocumentIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteResponse,
    DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/knowledge/documents/{document_id}",
    ...options,
  });
};

/**
 * Get Document
 * Get a document by its database ID.
 */
export const getDocumentApiV1KnowledgeDocumentsDocumentIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetDocumentApiV1KnowledgeDocumentsDocumentIdGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    GetDocumentApiV1KnowledgeDocumentsDocumentIdGetResponse,
    GetDocumentApiV1KnowledgeDocumentsDocumentIdGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/knowledge/documents/{document_id}",
    ...options,
  });
};

/**
 * Update Document
 * Update document metadata (title, description, domain, language).
 */
export const updateDocumentApiV1KnowledgeDocumentsDocumentIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchResponse,
    UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/knowledge/documents/{document_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Download Document
 * Download the original uploaded file.
 */
export const downloadDocumentApiV1KnowledgeDocumentsDocumentIdDownloadGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DownloadDocumentApiV1KnowledgeDocumentsDocumentIdDownloadGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    unknown,
    DownloadDocumentApiV1KnowledgeDocumentsDocumentIdDownloadGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/knowledge/documents/{document_id}/download",
    ...options,
  });
};

/**
 * Get Document Content
 * Get extracted text chunks for a document.
 */
export const getDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetResponse,
    GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/knowledge/documents/{document_id}/content",
    ...options,
  });
};

/**
 * List Domains
 * List all unique document domains.
 */
export const listDomainsApiV1KnowledgeDomainsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListDomainsApiV1KnowledgeDomainsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListDomainsApiV1KnowledgeDomainsGetResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/knowledge/domains",
    ...options,
  });
};

/**
 * List Tags
 * List all tags.
 */
export const listTagsApiV1KnowledgeTagsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListTagsApiV1KnowledgeTagsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListTagsApiV1KnowledgeTagsGetResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/knowledge/tags",
    ...options,
  });
};

/**
 * Create Tag
 * Create a new tag.
 */
export const createTagApiV1KnowledgeTagsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateTagApiV1KnowledgeTagsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateTagApiV1KnowledgeTagsPostResponse,
    CreateTagApiV1KnowledgeTagsPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/knowledge/tags",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete Tag
 * Delete a tag (CASCADE removes document associations).
 */
export const deleteTagApiV1KnowledgeTagsTagIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTagApiV1KnowledgeTagsTagIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteTagApiV1KnowledgeTagsTagIdDeleteResponse,
    DeleteTagApiV1KnowledgeTagsTagIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/knowledge/tags/{tag_id}",
    ...options,
  });
};

/**
 * Add Tags To Document
 * Add tags to a document.
 */
export const addTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostResponse,
    AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/knowledge/documents/{document_id}/tags",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Remove Tag From Document
 * Remove a tag from a document.
 */
export const removeTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteData,
      ThrowOnError
    >,
  ) => {
    return (options.client ?? _heyApiClient).delete<
      RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteResponse,
      RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteError,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/api/v1/knowledge/documents/{document_id}/tags/{tag_id}",
      ...options,
    });
  };

/**
 * Search Knowledge
 * Search the knowledge base with hybrid vector + fulltext search.
 */
export const searchKnowledgeApiV1KnowledgeSearchPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SearchKnowledgeApiV1KnowledgeSearchPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    SearchKnowledgeApiV1KnowledgeSearchPostResponse,
    SearchKnowledgeApiV1KnowledgeSearchPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/knowledge/search",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List Agencies
 * List all transit agencies.
 */
export const listAgenciesApiV1SchedulesAgenciesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListAgenciesApiV1SchedulesAgenciesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListAgenciesApiV1SchedulesAgenciesGetResponse,
    ListAgenciesApiV1SchedulesAgenciesGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/agencies",
    ...options,
  });
};

/**
 * Create Agency
 * Create a new transit agency.
 */
export const createAgencyApiV1SchedulesAgenciesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateAgencyApiV1SchedulesAgenciesPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateAgencyApiV1SchedulesAgenciesPostResponse,
    CreateAgencyApiV1SchedulesAgenciesPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/agencies",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List Routes
 * List routes with pagination and filtering.
 */
export const listRoutesApiV1SchedulesRoutesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListRoutesApiV1SchedulesRoutesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListRoutesApiV1SchedulesRoutesGetResponse,
    ListRoutesApiV1SchedulesRoutesGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/routes",
    ...options,
  });
};

/**
 * Create Route
 * Create a new route.
 */
export const createRouteApiV1SchedulesRoutesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateRouteApiV1SchedulesRoutesPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateRouteApiV1SchedulesRoutesPostResponse,
    CreateRouteApiV1SchedulesRoutesPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/routes",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete Route
 * Delete a route by its database ID.
 */
export const deleteRouteApiV1SchedulesRoutesRouteIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteRouteApiV1SchedulesRoutesRouteIdDeleteData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteRouteApiV1SchedulesRoutesRouteIdDeleteResponse,
    DeleteRouteApiV1SchedulesRoutesRouteIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/routes/{route_id}",
    ...options,
  });
};

/**
 * Get Route
 * Get a route by its database ID.
 */
export const getRouteApiV1SchedulesRoutesRouteIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetRouteApiV1SchedulesRoutesRouteIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetRouteApiV1SchedulesRoutesRouteIdGetResponse,
    GetRouteApiV1SchedulesRoutesRouteIdGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/routes/{route_id}",
    ...options,
  });
};

/**
 * Update Route
 * Update an existing route.
 */
export const updateRouteApiV1SchedulesRoutesRouteIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateRouteApiV1SchedulesRoutesRouteIdPatchData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateRouteApiV1SchedulesRoutesRouteIdPatchResponse,
    UpdateRouteApiV1SchedulesRoutesRouteIdPatchError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/routes/{route_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List Calendars
 * List service calendars with pagination.
 */
export const listCalendarsApiV1SchedulesCalendarsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListCalendarsApiV1SchedulesCalendarsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListCalendarsApiV1SchedulesCalendarsGetResponse,
    ListCalendarsApiV1SchedulesCalendarsGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/calendars",
    ...options,
  });
};

/**
 * Create Calendar
 * Create a new service calendar.
 */
export const createCalendarApiV1SchedulesCalendarsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCalendarApiV1SchedulesCalendarsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateCalendarApiV1SchedulesCalendarsPostResponse,
    CreateCalendarApiV1SchedulesCalendarsPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/calendars",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete Calendar
 * Delete a service calendar.
 */
export const deleteCalendarApiV1SchedulesCalendarsCalendarIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteCalendarApiV1SchedulesCalendarsCalendarIdDeleteData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteCalendarApiV1SchedulesCalendarsCalendarIdDeleteResponse,
    DeleteCalendarApiV1SchedulesCalendarsCalendarIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/calendars/{calendar_id}",
    ...options,
  });
};

/**
 * Get Calendar
 * Get a service calendar by ID.
 */
export const getCalendarApiV1SchedulesCalendarsCalendarIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCalendarApiV1SchedulesCalendarsCalendarIdGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    GetCalendarApiV1SchedulesCalendarsCalendarIdGetResponse,
    GetCalendarApiV1SchedulesCalendarsCalendarIdGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/calendars/{calendar_id}",
    ...options,
  });
};

/**
 * Update Calendar
 * Update an existing service calendar.
 */
export const updateCalendarApiV1SchedulesCalendarsCalendarIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateCalendarApiV1SchedulesCalendarsCalendarIdPatchData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateCalendarApiV1SchedulesCalendarsCalendarIdPatchResponse,
    UpdateCalendarApiV1SchedulesCalendarsCalendarIdPatchError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/calendars/{calendar_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Add Calendar Exception
 * Add a date exception to a service calendar.
 */
export const addCalendarExceptionApiV1SchedulesCalendarsCalendarIdExceptionsPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      AddCalendarExceptionApiV1SchedulesCalendarsCalendarIdExceptionsPostData,
      ThrowOnError
    >,
  ) => {
    return (options.client ?? _heyApiClient).post<
      AddCalendarExceptionApiV1SchedulesCalendarsCalendarIdExceptionsPostResponse,
      AddCalendarExceptionApiV1SchedulesCalendarsCalendarIdExceptionsPostError,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/api/v1/schedules/calendars/{calendar_id}/exceptions",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  };

/**
 * Remove Calendar Exception
 * Remove a calendar date exception.
 */
export const removeCalendarExceptionApiV1SchedulesCalendarExceptionsExceptionIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      RemoveCalendarExceptionApiV1SchedulesCalendarExceptionsExceptionIdDeleteData,
      ThrowOnError
    >,
  ) => {
    return (options.client ?? _heyApiClient).delete<
      RemoveCalendarExceptionApiV1SchedulesCalendarExceptionsExceptionIdDeleteResponse,
      RemoveCalendarExceptionApiV1SchedulesCalendarExceptionsExceptionIdDeleteError,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/api/v1/schedules/calendar-exceptions/{exception_id}",
      ...options,
    });
  };

/**
 * List Trips
 * List trips with pagination and filtering.
 */
export const listTripsApiV1SchedulesTripsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListTripsApiV1SchedulesTripsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListTripsApiV1SchedulesTripsGetResponse,
    ListTripsApiV1SchedulesTripsGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/trips",
    ...options,
  });
};

/**
 * Create Trip
 * Create a new trip.
 */
export const createTripApiV1SchedulesTripsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateTripApiV1SchedulesTripsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateTripApiV1SchedulesTripsPostResponse,
    CreateTripApiV1SchedulesTripsPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/trips",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete Trip
 * Delete a trip.
 */
export const deleteTripApiV1SchedulesTripsTripIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTripApiV1SchedulesTripsTripIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteTripApiV1SchedulesTripsTripIdDeleteResponse,
    DeleteTripApiV1SchedulesTripsTripIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/trips/{trip_id}",
    ...options,
  });
};

/**
 * Get Trip
 * Get a trip by ID with its stop times.
 */
export const getTripApiV1SchedulesTripsTripIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetTripApiV1SchedulesTripsTripIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetTripApiV1SchedulesTripsTripIdGetResponse,
    GetTripApiV1SchedulesTripsTripIdGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/trips/{trip_id}",
    ...options,
  });
};

/**
 * Update Trip
 * Update an existing trip.
 */
export const updateTripApiV1SchedulesTripsTripIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTripApiV1SchedulesTripsTripIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateTripApiV1SchedulesTripsTripIdPatchResponse,
    UpdateTripApiV1SchedulesTripsTripIdPatchError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/trips/{trip_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Replace Stop Times
 * Replace all stop times for a trip.
 */
export const replaceStopTimesApiV1SchedulesTripsTripIdStopTimesPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceStopTimesApiV1SchedulesTripsTripIdStopTimesPutData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).put<
    ReplaceStopTimesApiV1SchedulesTripsTripIdStopTimesPutResponse,
    ReplaceStopTimesApiV1SchedulesTripsTripIdStopTimesPutError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/trips/{trip_id}/stop-times",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Export Gtfs
 * Export schedule data as a GTFS-compliant ZIP file.
 */
export const exportGtfsApiV1SchedulesExportGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ExportGtfsApiV1SchedulesExportGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    unknown,
    ExportGtfsApiV1SchedulesExportGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/export",
    ...options,
  });
};

/**
 * Import Gtfs
 * Import schedule data from a GTFS ZIP file.
 */
export const importGtfsApiV1SchedulesImportPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ImportGtfsApiV1SchedulesImportPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ImportGtfsApiV1SchedulesImportPostResponse,
    ImportGtfsApiV1SchedulesImportPostError,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/import",
    ...options,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
  });
};

/**
 * Validate Schedule
 * Validate referential integrity of schedule data.
 */
export const validateScheduleApiV1SchedulesValidatePost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ValidateScheduleApiV1SchedulesValidatePostData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? _heyApiClient).post<
    ValidateScheduleApiV1SchedulesValidatePostResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/schedules/validate",
    ...options,
  });
};

/**
 * List Drivers
 * List drivers with pagination and optional filters.
 */
export const listDriversApiV1DriversGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListDriversApiV1DriversGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListDriversApiV1DriversGetResponse,
    ListDriversApiV1DriversGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/drivers/",
    ...options,
  });
};

/**
 * Create Driver
 * Create a new driver.
 */
export const createDriverApiV1DriversPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateDriverApiV1DriversPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateDriverApiV1DriversPostResponse,
    CreateDriverApiV1DriversPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/drivers/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete Driver
 * Delete a driver by database ID.
 */
export const deleteDriverApiV1DriversDriverIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteDriverApiV1DriversDriverIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteDriverApiV1DriversDriverIdDeleteResponse,
    DeleteDriverApiV1DriversDriverIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/drivers/{driver_id}",
    ...options,
  });
};

/**
 * Get Driver
 * Get a driver by database ID.
 */
export const getDriverApiV1DriversDriverIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetDriverApiV1DriversDriverIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetDriverApiV1DriversDriverIdGetResponse,
    GetDriverApiV1DriversDriverIdGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/drivers/{driver_id}",
    ...options,
  });
};

/**
 * Update Driver
 * Update an existing driver.
 */
export const updateDriverApiV1DriversDriverIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateDriverApiV1DriversDriverIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateDriverApiV1DriversDriverIdPatchResponse,
    UpdateDriverApiV1DriversDriverIdPatchError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/drivers/{driver_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List Events
 * List operational events with optional date range and driver filters.
 *
 * Requires admin or dispatcher role. Operational data is restricted.
 */
export const listEventsApiV1EventsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListEventsApiV1EventsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListEventsApiV1EventsGetResponse,
    ListEventsApiV1EventsGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/events/",
    ...options,
  });
};

/**
 * Create Event
 * Create a new operational event.
 */
export const createEventApiV1EventsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateEventApiV1EventsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateEventApiV1EventsPostResponse,
    CreateEventApiV1EventsPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/events/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List Events By Driver
 * List operational events for a specific driver.
 *
 * Requires admin or dispatcher role. Supports pagination and date range filters.
 */
export const listEventsByDriverApiV1EventsByDriverDriverIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListEventsByDriverApiV1EventsByDriverDriverIdGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    ListEventsByDriverApiV1EventsByDriverDriverIdGetResponse,
    ListEventsByDriverApiV1EventsByDriverDriverIdGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/events/by-driver/{driver_id}",
    ...options,
  });
};

/**
 * Delete Event
 * Delete an operational event.
 */
export const deleteEventApiV1EventsEventIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteEventApiV1EventsEventIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteEventApiV1EventsEventIdDeleteResponse,
    DeleteEventApiV1EventsEventIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/events/{event_id}",
    ...options,
  });
};

/**
 * Get Event
 * Get an operational event by ID.
 *
 * Requires admin or dispatcher role. Operational data is restricted.
 */
export const getEventApiV1EventsEventIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetEventApiV1EventsEventIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetEventApiV1EventsEventIdGetResponse,
    GetEventApiV1EventsEventIdGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/events/{event_id}",
    ...options,
  });
};

/**
 * Update Event
 * Update an existing operational event.
 */
export const updateEventApiV1EventsEventIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateEventApiV1EventsEventIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateEventApiV1EventsEventIdPatchResponse,
    UpdateEventApiV1EventsEventIdPatchError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/events/{event_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List Skills
 * List agent skills with optional filters.
 *
 * Requires authentication. All skill data access is restricted.
 */
export const listSkillsApiV1SkillsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListSkillsApiV1SkillsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListSkillsApiV1SkillsGetResponse,
    ListSkillsApiV1SkillsGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/skills/",
    ...options,
  });
};

/**
 * Create Skill
 * Create a new agent skill. Admin only.
 */
export const createSkillApiV1SkillsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateSkillApiV1SkillsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateSkillApiV1SkillsPostResponse,
    CreateSkillApiV1SkillsPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/skills/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete Skill
 * Delete an agent skill. Admin only.
 */
export const deleteSkillApiV1SkillsSkillIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteSkillApiV1SkillsSkillIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteSkillApiV1SkillsSkillIdDeleteResponse,
    DeleteSkillApiV1SkillsSkillIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/skills/{skill_id}",
    ...options,
  });
};

/**
 * Get Skill
 * Get an agent skill by ID.
 *
 * Requires authentication. All skill data access is restricted.
 */
export const getSkillApiV1SkillsSkillIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSkillApiV1SkillsSkillIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetSkillApiV1SkillsSkillIdGetResponse,
    GetSkillApiV1SkillsSkillIdGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/skills/{skill_id}",
    ...options,
  });
};

/**
 * Update Skill
 * Update an existing agent skill. Admin only.
 */
export const updateSkillApiV1SkillsSkillIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateSkillApiV1SkillsSkillIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateSkillApiV1SkillsSkillIdPatchResponse,
    UpdateSkillApiV1SkillsSkillIdPatchError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/skills/{skill_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Seed Skills
 * Seed default skills. Admin only. Only seeds when table is empty.
 */
export const seedSkillsApiV1SkillsSeedPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SeedSkillsApiV1SkillsSeedPostData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    SeedSkillsApiV1SkillsSeedPostResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/skills/seed",
    ...options,
  });
};

/**
 * List Vehicles
 * List vehicles with pagination and optional filters.
 */
export const listVehiclesApiV1VehiclesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListVehiclesApiV1VehiclesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListVehiclesApiV1VehiclesGetResponse,
    ListVehiclesApiV1VehiclesGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vehicles/",
    ...options,
  });
};

/**
 * Create Vehicle
 * Create a new vehicle.
 */
export const createVehicleApiV1VehiclesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateVehicleApiV1VehiclesPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateVehicleApiV1VehiclesPostResponse,
    CreateVehicleApiV1VehiclesPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vehicles/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete Vehicle
 * Delete a vehicle by database ID.
 */
export const deleteVehicleApiV1VehiclesVehicleIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteVehicleApiV1VehiclesVehicleIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteVehicleApiV1VehiclesVehicleIdDeleteResponse,
    DeleteVehicleApiV1VehiclesVehicleIdDeleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vehicles/{vehicle_id}",
    ...options,
  });
};

/**
 * Get Vehicle
 * Get a vehicle by database ID.
 */
export const getVehicleApiV1VehiclesVehicleIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetVehicleApiV1VehiclesVehicleIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetVehicleApiV1VehiclesVehicleIdGetResponse,
    GetVehicleApiV1VehiclesVehicleIdGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vehicles/{vehicle_id}",
    ...options,
  });
};

/**
 * Update Vehicle
 * Update an existing vehicle.
 */
export const updateVehicleApiV1VehiclesVehicleIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateVehicleApiV1VehiclesVehicleIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateVehicleApiV1VehiclesVehicleIdPatchResponse,
    UpdateVehicleApiV1VehiclesVehicleIdPatchError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vehicles/{vehicle_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Assign Driver
 * Assign or unassign a driver to/from a vehicle.
 */
export const assignDriverApiV1VehiclesVehicleIdAssignDriverPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AssignDriverApiV1VehiclesVehicleIdAssignDriverPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    AssignDriverApiV1VehiclesVehicleIdAssignDriverPostResponse,
    AssignDriverApiV1VehiclesVehicleIdAssignDriverPostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vehicles/{vehicle_id}/assign-driver",
    ...options,
  });
};

/**
 * Get Maintenance History
 * Get maintenance history for a vehicle.
 */
export const getMaintenanceHistoryApiV1VehiclesVehicleIdMaintenanceGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetMaintenanceHistoryApiV1VehiclesVehicleIdMaintenanceGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    GetMaintenanceHistoryApiV1VehiclesVehicleIdMaintenanceGetResponse,
    GetMaintenanceHistoryApiV1VehiclesVehicleIdMaintenanceGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vehicles/{vehicle_id}/maintenance",
    ...options,
  });
};

/**
 * Create Maintenance Record
 * Add a maintenance record to a vehicle.
 */
export const createMaintenanceRecordApiV1VehiclesVehicleIdMaintenancePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateMaintenanceRecordApiV1VehiclesVehicleIdMaintenancePostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateMaintenanceRecordApiV1VehiclesVehicleIdMaintenancePostResponse,
    CreateMaintenanceRecordApiV1VehiclesVehicleIdMaintenancePostError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vehicles/{vehicle_id}/maintenance",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Export Netex
 * Export schedule data as NeTEx EPIP XML.
 */
export const exportNetexApiV1ComplianceNetexGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ExportNetexApiV1ComplianceNetexGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    unknown,
    ExportNetexApiV1ComplianceNetexGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/compliance/netex",
    ...options,
  });
};

/**
 * Get Siri Vm
 * Get real-time vehicle positions as SIRI-VM XML.
 */
export const getSiriVmApiV1ComplianceSiriVmGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetSiriVmApiV1ComplianceSiriVmGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    unknown,
    GetSiriVmApiV1ComplianceSiriVmGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/compliance/siri/vm",
    ...options,
  });
};

/**
 * Get Siri Sm
 * Get stop departure predictions as SIRI-SM XML.
 */
export const getSiriSmApiV1ComplianceSiriSmGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSiriSmApiV1ComplianceSiriSmGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    unknown,
    GetSiriSmApiV1ComplianceSiriSmGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/compliance/siri/sm",
    ...options,
  });
};

/**
 * Get Export Status
 * Get export availability status with entity counts.
 */
export const getExportStatusApiV1ComplianceStatusGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetExportStatusApiV1ComplianceStatusGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetExportStatusApiV1ComplianceStatusGetResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/compliance/status",
    ...options,
  });
};

/**
 * Get Fleet Summary
 * Get fleet status breakdown with operational alerts.
 *
 * Args:
 * request: The incoming HTTP request (used for rate limiting).
 * db: Async database session.
 *
 * Returns:
 * FleetSummaryResponse with counts by type/status and alerts.
 */
export const getFleetSummaryApiV1AnalyticsFleetSummaryGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetFleetSummaryApiV1AnalyticsFleetSummaryGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetFleetSummaryApiV1AnalyticsFleetSummaryGetResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/analytics/fleet-summary",
    ...options,
  });
};

/**
 * Get Driver Summary
 * Get driver coverage breakdown with expiry alerts.
 *
 * Args:
 * request: The incoming HTTP request (used for rate limiting).
 * db: Async database session.
 *
 * Returns:
 * DriverSummaryResponse with counts by shift/status and alerts.
 */
export const getDriverSummaryApiV1AnalyticsDriverSummaryGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetDriverSummaryApiV1AnalyticsDriverSummaryGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetDriverSummaryApiV1AnalyticsDriverSummaryGetResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/analytics/driver-summary",
    ...options,
  });
};

/**
 * Get On Time Performance
 * Get on-time adherence metrics from live GTFS-RT data.
 *
 * Args:
 * request: The incoming HTTP request (used for rate limiting).
 * route_id: Optional GTFS route ID for single-route analysis.
 * date: Service date as YYYY-MM-DD. Defaults to today (Riga timezone).
 * time_from: Start of analysis window (HH:MM).
 * time_until: End of analysis window (HH:MM).
 * db: Async database session.
 *
 * Returns:
 * OnTimePerformanceResponse with per-route and network metrics.
 */
export const getOnTimePerformanceApiV1AnalyticsOnTimePerformanceGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetOnTimePerformanceApiV1AnalyticsOnTimePerformanceGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetOnTimePerformanceApiV1AnalyticsOnTimePerformanceGetResponse,
    GetOnTimePerformanceApiV1AnalyticsOnTimePerformanceGetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/analytics/on-time-performance",
    ...options,
  });
};

/**
 * Get Overview
 * Get combined dashboard summary with fleet, driver, and on-time data.
 *
 * On-time performance degrades gracefully — if transit data is unavailable,
 * the overview still returns fleet and driver summaries with an empty on-time
 * section.
 *
 * Args:
 * request: The incoming HTTP request (used for rate limiting).
 * db: Async database session.
 *
 * Returns:
 * AnalyticsOverviewResponse with all three summaries.
 */
export const getOverviewApiV1AnalyticsOverviewGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetOverviewApiV1AnalyticsOverviewGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetOverviewApiV1AnalyticsOverviewGetResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/analytics/overview",
    ...options,
  });
};

/**
 * Read Root
 * Root endpoint providing API information.
 *
 * Returns:
 * Dict containing application name, version, and docs URL.
 */
export const readRootGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadRootGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadRootGetResponse,
    unknown,
    ThrowOnError
  >({
    url: "/",
    ...options,
  });
};
