"""initial schema

Revision ID: 16befcf37286
Revises:
Create Date: 2026-02-21 14:34:26.252206

"""

from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16befcf37286"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create pgvector extension for embedding columns
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gtfs_agency_id", sa.String(length=50), nullable=False),
        sa.Column("agency_name", sa.String(length=200), nullable=False),
        sa.Column("agency_url", sa.String(length=500), nullable=True),
        sa.Column("agency_timezone", sa.String(length=50), nullable=False),
        sa.Column("agency_lang", sa.String(length=5), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agencies_gtfs_agency_id"), "agencies", ["gtfs_agency_id"], unique=True)
    op.create_index(op.f("ix_agencies_id"), "agencies", ["id"], unique=False)
    op.create_table(
        "calendars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gtfs_service_id", sa.String(length=50), nullable=False),
        sa.Column("monday", sa.Boolean(), nullable=False),
        sa.Column("tuesday", sa.Boolean(), nullable=False),
        sa.Column("wednesday", sa.Boolean(), nullable=False),
        sa.Column("thursday", sa.Boolean(), nullable=False),
        sa.Column("friday", sa.Boolean(), nullable=False),
        sa.Column("saturday", sa.Boolean(), nullable=False),
        sa.Column("sunday", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calendars_gtfs_service_id"), "calendars", ["gtfs_service_id"], unique=True
    )
    op.create_index(op.f("ix_calendars_id"), "calendars", ["id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column("domain", sa.String(length=50), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_domain"), "documents", ["domain"], unique=False)
    op.create_index(op.f("ix_documents_id"), "documents", ["id"], unique=False)
    op.create_table(
        "stops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gtfs_stop_id", sa.String(length=50), nullable=False),
        sa.Column("stop_name", sa.String(length=200), nullable=False),
        sa.Column("stop_lat", sa.Float(), nullable=True),
        sa.Column("stop_lon", sa.Float(), nullable=True),
        sa.Column("stop_desc", sa.Text(), nullable=True),
        sa.Column("location_type", sa.Integer(), nullable=False),
        sa.Column("parent_station_id", sa.Integer(), nullable=True),
        sa.Column("wheelchair_boarding", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_station_id"],
            ["stops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stops_gtfs_stop_id"), "stops", ["gtfs_stop_id"], unique=True)
    op.create_index(op.f("ix_stops_id"), "stops", ["id"], unique=False)
    op.create_index(op.f("ix_stops_stop_name"), "stops", ["stop_name"], unique=False)
    op.create_table(
        "calendar_dates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("calendar_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("exception_type", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["calendar_id"], ["calendars.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calendar_dates_calendar_id"), "calendar_dates", ["calendar_id"], unique=False
    )
    op.create_index(op.f("ix_calendar_dates_id"), "calendar_dates", ["id"], unique=False)
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"), "document_chunks", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_document_chunks_id"), "document_chunks", ["id"], unique=False)
    op.create_table(
        "routes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gtfs_route_id", sa.String(length=50), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("route_short_name", sa.String(length=50), nullable=False),
        sa.Column("route_long_name", sa.String(length=200), nullable=False),
        sa.Column("route_type", sa.Integer(), nullable=False),
        sa.Column("route_color", sa.String(length=6), nullable=True),
        sa.Column("route_text_color", sa.String(length=6), nullable=True),
        sa.Column("route_sort_order", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agency_id"], ["agencies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_routes_agency_id"), "routes", ["agency_id"], unique=False)
    op.create_index(op.f("ix_routes_gtfs_route_id"), "routes", ["gtfs_route_id"], unique=True)
    op.create_index(op.f("ix_routes_id"), "routes", ["id"], unique=False)
    op.create_index(
        op.f("ix_routes_route_short_name"), "routes", ["route_short_name"], unique=False
    )
    op.create_table(
        "trips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gtfs_trip_id", sa.String(length=100), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("calendar_id", sa.Integer(), nullable=False),
        sa.Column("direction_id", sa.Integer(), nullable=True),
        sa.Column("trip_headsign", sa.String(length=200), nullable=True),
        sa.Column("block_id", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["calendar_id"], ["calendars.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trips_calendar_id"), "trips", ["calendar_id"], unique=False)
    op.create_index(op.f("ix_trips_gtfs_trip_id"), "trips", ["gtfs_trip_id"], unique=True)
    op.create_index(op.f("ix_trips_id"), "trips", ["id"], unique=False)
    op.create_index(op.f("ix_trips_route_id"), "trips", ["route_id"], unique=False)
    op.create_table(
        "stop_times",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("stop_id", sa.Integer(), nullable=False),
        sa.Column("stop_sequence", sa.Integer(), nullable=False),
        sa.Column("arrival_time", sa.String(length=8), nullable=False),
        sa.Column("departure_time", sa.String(length=8), nullable=False),
        sa.Column("pickup_type", sa.Integer(), nullable=False),
        sa.Column("drop_off_type", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["stop_id"], ["stops.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stop_times_id"), "stop_times", ["id"], unique=False)
    op.create_index(op.f("ix_stop_times_stop_id"), "stop_times", ["stop_id"], unique=False)
    op.create_index(op.f("ix_stop_times_trip_id"), "stop_times", ["trip_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stop_times_trip_id"), table_name="stop_times")
    op.drop_index(op.f("ix_stop_times_stop_id"), table_name="stop_times")
    op.drop_index(op.f("ix_stop_times_id"), table_name="stop_times")
    op.drop_table("stop_times")
    op.drop_index(op.f("ix_trips_route_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_gtfs_trip_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_calendar_id"), table_name="trips")
    op.drop_table("trips")
    op.drop_index(op.f("ix_routes_route_short_name"), table_name="routes")
    op.drop_index(op.f("ix_routes_id"), table_name="routes")
    op.drop_index(op.f("ix_routes_gtfs_route_id"), table_name="routes")
    op.drop_index(op.f("ix_routes_agency_id"), table_name="routes")
    op.drop_table("routes")
    op.drop_index(op.f("ix_document_chunks_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_calendar_dates_id"), table_name="calendar_dates")
    op.drop_index(op.f("ix_calendar_dates_calendar_id"), table_name="calendar_dates")
    op.drop_table("calendar_dates")
    op.drop_index(op.f("ix_stops_stop_name"), table_name="stops")
    op.drop_index(op.f("ix_stops_id"), table_name="stops")
    op.drop_index(op.f("ix_stops_gtfs_stop_id"), table_name="stops")
    op.drop_table("stops")
    op.drop_index(op.f("ix_documents_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_domain"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_calendars_id"), table_name="calendars")
    op.drop_index(op.f("ix_calendars_gtfs_service_id"), table_name="calendars")
    op.drop_table("calendars")
    op.drop_index(op.f("ix_agencies_id"), table_name="agencies")
    op.drop_index(op.f("ix_agencies_gtfs_agency_id"), table_name="agencies")
    op.drop_table("agencies")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
