"""add vehicles and maintenance records tables

Revision ID: a74dcc53a4df
Revises: b039c337be87
Create Date: 2026-02-27 13:41:54.794712

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a74dcc53a4df"
down_revision: str | Sequence[str] | None = "b039c337be87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fleet_number", sa.String(length=20), nullable=False),
        sa.Column("vehicle_type", sa.String(length=20), nullable=False),
        sa.Column("license_plate", sa.String(length=20), nullable=False),
        sa.Column("manufacturer", sa.String(length=100), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("model_year", sa.Integer(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_driver_id", sa.Integer(), nullable=True),
        sa.Column("mileage_km", sa.Integer(), nullable=False),
        sa.Column("qualified_route_ids", sa.String(length=500), nullable=True),
        sa.Column("registration_expiry", sa.Date(), nullable=True),
        sa.Column("next_maintenance_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["current_driver_id"], ["drivers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicles_fleet_number"), "vehicles", ["fleet_number"], unique=True)
    op.create_index(op.f("ix_vehicles_id"), "vehicles", ["id"], unique=False)
    op.create_table(
        "maintenance_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("maintenance_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("performed_date", sa.Date(), nullable=False),
        sa.Column("mileage_at_service", sa.Integer(), nullable=True),
        sa.Column("cost_eur", sa.Float(), nullable=True),
        sa.Column("next_scheduled_date", sa.Date(), nullable=True),
        sa.Column("performed_by", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_maintenance_records_id"), "maintenance_records", ["id"], unique=False)
    op.create_index(
        op.f("ix_maintenance_records_vehicle_id"),
        "maintenance_records",
        ["vehicle_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_maintenance_records_vehicle_id"), table_name="maintenance_records")
    op.drop_index(op.f("ix_maintenance_records_id"), table_name="maintenance_records")
    op.drop_table("maintenance_records")
    op.drop_index(op.f("ix_vehicles_id"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_fleet_number"), table_name="vehicles")
    op.drop_table("vehicles")
    # ### end Alembic commands ###
